CREATE TABLE street (
    ID INTEGER UNIQUE,
    NAME TEXT
);

CREATE TABLE crime (
    ID INTEGER UNIQUE,
    PERSISTENT_ID TEXT,
    category TEXT,
    location_type TEXT,
    context TEXT,    
    location_subtype TEXT,
    MONTH_CRIME DATE,
    STREET_ID INTEGER
);

CREATE TABLE locations(
    LATITUDE DOUBLE PRECISION,
    LONGITUDE DOUBLE PRECISION,
    STREET_ID INTEGER,
    CRIME_ID INTEGER
);

CREATE TABLE outcome_status (
    CATEGORY TEXT,
    MONTH_CRIME DATE,
    CRIME_ID INTEGER
);


ALTER TABLE locations
ADD CONSTRAINT FK_locations_street
FOREIGN KEY (STREET_ID)
REFERENCES street(ID)
ON DELETE SET NULL;

ALTER TABLE locations
ADD CONSTRAINT FK_locations_crime
FOREIGN KEY (CRIME_ID)
REFERENCES crime(ID)
ON DELETE SET NULL;


ALTER TABLE crime
ADD CONSTRAINT FK_crime
FOREIGN KEY (STREET_ID)
REFERENCES street(ID)
ON DELETE SET NULL;

ALTER TABLE outcome_status
ADD CONSTRAINT FK_outcome_status
FOREIGN KEY (CRIME_ID)
REFERENCES crime(ID)
ON DELETE SET NULL;
